### ISSUE TITLE
Composer run-time exception after update to 1.3.2

### ISSUE THREAD

**Issue by NicholasTurner** [brodkinca/BCA-Laravel-Inspect#4]
Updating Composer to release 1.3.2 causes a run-time exception during autoload generation:

[RuntimeException]
  Could not scan for classes inside "/home/dev/webapp/vendor/bca/laravel-inspect/tests/" which does not appear to be a file nor a folder

It appears that the .gitattributes file (uploaded 3 days ago in commit 00eba9f918031d7f181365ada27f0266613d758a) is causing Composer to not download the test directory.

**Comment by brodkin** [comment]
Sorry about that... I'll get a fix out ASAP.

Until then using a --prefer-source flag should clear up the issue.
—
Sent from Mailbox

On Thu, Jun 12, 2014 at 11:07 AM, Nicholas Turner
notifications@github.com wrote:

> Updating Composer to release 1.3.2 causes a run-time exception during autoload generation:
> [RuntimeException]
>   Could not scan for classes inside "/home/dev/webapp/vendor/bca/laravel-inspect/tests/" which does not appear to be a file nor a folder
> 
> ## It appears that the .gitattributes file (uploaded 3 days ago in commit 00eba9f918031d7f181365ada27f0266613d758a) is causing Composer to not download the test directory.
> 
> Reply to this email directly or view it on GitHub:
> 
> ## https://github.com/brodkinca/BCA-Laravel-Inspect/issues/4
> 
> Brodkin CyberArts
> http://brodkinca.com | 310.220.0590
> DESIGN. DEVELOPMENT. CONSULTING.

Information contained in this email or any attachment may be of 
a confidential nature which should not be disclosed to, copied or used by 
anyone other than the addressee. If you receive this email in error, please 
delete the email from your computer. Do not post anything in this email to 
any online forum without express permission of the sender. No pixels were 
harmed in the making of this disclaimer.

**Comment by NicholasTurner** [comment]
No worries, we fixed it short-term by grabbing an old commit.

**Comment by Sonique** [comment]
Same issue

**Comment by XMichaelMichaelX** [comment]
could you add this fix to release because I've faced with this as well
latest stable version still have this issue
thanks

**Comment by brodkin** [comment]
Sorry about that, I prepared the release and everything--apparently I just forgot to push it up to GitHub. Version 1.3.3 should take care of the problem.
